// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at, user_agent, ip_address)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, issued_at, expires_at, revoked_at, user_agent, ip_address
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	TokenHash string      `json:"token_hash"`
	ExpiresAt time.Time   `json:"expires_at"`
	UserAgent pgtype.Text `json:"user_agent"`
	IpAddress pgtype.Text `json:"ip_address"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.IpAddress,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, issued_at, expires_at, revoked_at, user_agent, ip_address
FROM refresh_tokens
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.IpAddress,
	)
	return i, err
}

const getUserCredentialsByEmail = `-- name: GetUserCredentialsByEmail :one
SELECT id, password, is_active, deleted_at
FROM users
WHERE LOWER(email) = LOWER($1)
LIMIT 1
`

type GetUserCredentialsByEmailRow struct {
	ID        uuid.UUID          `json:"id"`
	Password  string             `json:"password"`
	IsActive  bool               `json:"is_active"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetUserCredentialsByEmail(ctx context.Context, lower string) (GetUserCredentialsByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserCredentialsByEmail, lower)
	var i GetUserCredentialsByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Password,
		&i.IsActive,
		&i.DeletedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}
