// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: boards.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (project_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, project_id, name, description, created_at, updated_at
`

type CreateBoardParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

type CreateBoardRow struct {
	ID          uuid.UUID `json:"id"`
	ProjectID   uuid.UUID `json:"project_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (CreateBoardRow, error) {
	row := q.db.QueryRow(ctx, createBoard, arg.ProjectID, arg.Name, arg.Description)
	var i CreateBoardRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const forceDeleteBoard = `-- name: ForceDeleteBoard :exec
DELETE FROM boards WHERE id = $1
`

func (q *Queries) ForceDeleteBoard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, forceDeleteBoard, id)
	return err
}

const getBoardByID = `-- name: GetBoardByID :one
SELECT id, project_id, name, description, created_at, updated_at
FROM boards
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

type GetBoardByIDRow struct {
	ID          uuid.UUID `json:"id"`
	ProjectID   uuid.UUID `json:"project_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) GetBoardByID(ctx context.Context, id uuid.UUID) (GetBoardByIDRow, error) {
	row := q.db.QueryRow(ctx, getBoardByID, id)
	var i GetBoardByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBoardsByProject = `-- name: ListBoardsByProject :many
SELECT id, project_id, name, description, created_at, updated_at
FROM boards
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListBoardsByProjectRow struct {
	ID          uuid.UUID `json:"id"`
	ProjectID   uuid.UUID `json:"project_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListBoardsByProject(ctx context.Context, projectID uuid.UUID) ([]ListBoardsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listBoardsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBoardsByProjectRow
	for rows.Next() {
		var i ListBoardsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteBoard = `-- name: SoftDeleteBoard :exec
UPDATE boards SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteBoard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteBoard, id)
	return err
}
