// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: checklists.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChecklist = `-- name: CreateChecklist :one
INSERT INTO checklists (task_id, title, position)
VALUES ($1, $2, $3)
RETURNING id, task_id, title, position, created_at
`

type CreateChecklistParams struct {
	TaskID   uuid.UUID `json:"task_id"`
	Title    string    `json:"title"`
	Position float64   `json:"position"`
}

func (q *Queries) CreateChecklist(ctx context.Context, arg CreateChecklistParams) (Checklist, error) {
	row := q.db.QueryRow(ctx, createChecklist, arg.TaskID, arg.Title, arg.Position)
	var i Checklist
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createChecklistItem = `-- name: CreateChecklistItem :one
INSERT INTO checklist_items (checklist_id, content, is_done, position)
VALUES ($1, $2, COALESCE($3, FALSE), $4)
RETURNING id, checklist_id, content, is_done, position, created_at
`

type CreateChecklistItemParams struct {
	ChecklistID uuid.UUID   `json:"checklist_id"`
	Content     string      `json:"content"`
	Column3     interface{} `json:"column_3"`
	Position    float64     `json:"position"`
}

func (q *Queries) CreateChecklistItem(ctx context.Context, arg CreateChecklistItemParams) (ChecklistItem, error) {
	row := q.db.QueryRow(ctx, createChecklistItem,
		arg.ChecklistID,
		arg.Content,
		arg.Column3,
		arg.Position,
	)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.ChecklistID,
		&i.Content,
		&i.IsDone,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChecklist = `-- name: DeleteChecklist :exec
DELETE
FROM checklists
WHERE id = $1
`

func (q *Queries) DeleteChecklist(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChecklist, id)
	return err
}

const deleteChecklistItem = `-- name: DeleteChecklistItem :exec
DELETE
FROM checklist_items
WHERE id = $1
`

func (q *Queries) DeleteChecklistItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChecklistItem, id)
	return err
}

const listChecklistItems = `-- name: ListChecklistItems :many
SELECT id, checklist_id, content, is_done, position, created_at
FROM checklist_items
WHERE checklist_id = $1
ORDER BY position ASC
`

func (q *Queries) ListChecklistItems(ctx context.Context, checklistID uuid.UUID) ([]ChecklistItem, error) {
	rows, err := q.db.Query(ctx, listChecklistItems, checklistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChecklistItem
	for rows.Next() {
		var i ChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.ChecklistID,
			&i.Content,
			&i.IsDone,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChecklists = `-- name: ListChecklists :many
SELECT id, task_id, title, position, created_at
FROM checklists
WHERE task_id = $1
ORDER BY position ASC
`

func (q *Queries) ListChecklists(ctx context.Context, taskID uuid.UUID) ([]Checklist, error) {
	rows, err := q.db.Query(ctx, listChecklists, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Checklist
	for rows.Next() {
		var i Checklist
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Title,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextChecklistItemPosition = `-- name: NextChecklistItemPosition :one
SELECT f_next_checklist_item_position($1) AS next_pos
`

// Items
func (q *Queries) NextChecklistItemPosition(ctx context.Context, pChecklistID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, nextChecklistItemPosition, pChecklistID)
	var next_pos float64
	err := row.Scan(&next_pos)
	return next_pos, err
}

const nextChecklistPosition = `-- name: NextChecklistPosition :one
SELECT f_next_checklist_position($1) AS next_pos
`

func (q *Queries) NextChecklistPosition(ctx context.Context, pTaskID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, nextChecklistPosition, pTaskID)
	var next_pos float64
	err := row.Scan(&next_pos)
	return next_pos, err
}

const renameChecklist = `-- name: RenameChecklist :one
UPDATE checklists
SET title    = COALESCE($2, title),
    position = COALESCE($3, position)
WHERE id = $1
RETURNING id, task_id, title, position, created_at
`

type RenameChecklistParams struct {
	ID       uuid.UUID     `json:"id"`
	Title    pgtype.Text   `json:"title"`
	Position pgtype.Float8 `json:"position"`
}

func (q *Queries) RenameChecklist(ctx context.Context, arg RenameChecklistParams) (Checklist, error) {
	row := q.db.QueryRow(ctx, renameChecklist, arg.ID, arg.Title, arg.Position)
	var i Checklist
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const updateChecklistItem = `-- name: UpdateChecklistItem :one
UPDATE checklist_items
SET content  = COALESCE($2, content),
    is_done  = COALESCE($3, is_done),
    position = COALESCE($4, position)
WHERE id = $1
RETURNING id, checklist_id, content, is_done, position, created_at
`

type UpdateChecklistItemParams struct {
	ID       uuid.UUID     `json:"id"`
	Content  pgtype.Text   `json:"content"`
	IsDone   pgtype.Bool   `json:"is_done"`
	Position pgtype.Float8 `json:"position"`
}

func (q *Queries) UpdateChecklistItem(ctx context.Context, arg UpdateChecklistItemParams) (ChecklistItem, error) {
	row := q.db.QueryRow(ctx, updateChecklistItem,
		arg.ID,
		arg.Content,
		arg.IsDone,
		arg.Position,
	)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.ChecklistID,
		&i.Content,
		&i.IsDone,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
