// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: columns.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createColumn = `-- name: CreateColumn :one
INSERT INTO columns (board_id, name, wip_limit, position)
VALUES ($1::uuid,
        $2,
        $3::int4, -- ← nullable INT, cast ke int4
        $4::float8 -- ← NOT NULL double precision
       )
RETURNING id, board_id, name, wip_limit, position, created_at, updated_at
`

type CreateColumnParams struct {
	BoardID  uuid.UUID   `json:"board_id"`
	Name     string      `json:"name"`
	WipLimit pgtype.Int4 `json:"wip_limit"`
	Position float64     `json:"position"`
}

type CreateColumnRow struct {
	ID        uuid.UUID   `json:"id"`
	BoardID   uuid.UUID   `json:"board_id"`
	Name      string      `json:"name"`
	WipLimit  pgtype.Int4 `json:"wip_limit"`
	Position  float64     `json:"position"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (CreateColumnRow, error) {
	row := q.db.QueryRow(ctx, createColumn,
		arg.BoardID,
		arg.Name,
		arg.WipLimit,
		arg.Position,
	)
	var i CreateColumnRow
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.WipLimit,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listColumnsByBoard = `-- name: ListColumnsByBoard :many
SELECT id, board_id, name, wip_limit, position, created_at, updated_at
FROM columns
WHERE board_id = $1
  AND deleted_at IS NULL
ORDER BY position ASC
`

type ListColumnsByBoardRow struct {
	ID        uuid.UUID   `json:"id"`
	BoardID   uuid.UUID   `json:"board_id"`
	Name      string      `json:"name"`
	WipLimit  pgtype.Int4 `json:"wip_limit"`
	Position  float64     `json:"position"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

func (q *Queries) ListColumnsByBoard(ctx context.Context, boardID uuid.UUID) ([]ListColumnsByBoardRow, error) {
	rows, err := q.db.Query(ctx, listColumnsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListColumnsByBoardRow
	for rows.Next() {
		var i ListColumnsByBoardRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.WipLimit,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextColumnPosition = `-- name: NextColumnPosition :one
SELECT f_next_column_position($1) AS next_pos
`

func (q *Queries) NextColumnPosition(ctx context.Context, pBoardID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, nextColumnPosition, pBoardID)
	var next_pos float64
	err := row.Scan(&next_pos)
	return next_pos, err
}

const softDeleteColumn = `-- name: SoftDeleteColumn :exec
UPDATE columns
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteColumn(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteColumn, id)
	return err
}

const updateColumn = `-- name: UpdateColumn :one
UPDATE columns
SET name       = COALESCE($2, name),
    wip_limit  = COALESCE($3::int4, wip_limit), -- ← cast
    position   = COALESCE($4::float8, position), -- ← cast
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, board_id, name, wip_limit, position, created_at, updated_at
`

type UpdateColumnParams struct {
	ID       uuid.UUID     `json:"id"`
	Name     pgtype.Text   `json:"name"`
	WipLimit pgtype.Int4   `json:"wip_limit"`
	Position pgtype.Float8 `json:"position"`
}

type UpdateColumnRow struct {
	ID        uuid.UUID   `json:"id"`
	BoardID   uuid.UUID   `json:"board_id"`
	Name      string      `json:"name"`
	WipLimit  pgtype.Int4 `json:"wip_limit"`
	Position  float64     `json:"position"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateColumn(ctx context.Context, arg UpdateColumnParams) (UpdateColumnRow, error) {
	row := q.db.QueryRow(ctx, updateColumn,
		arg.ID,
		arg.Name,
		arg.WipLimit,
		arg.Position,
	)
	var i UpdateColumnRow
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.WipLimit,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
