// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: labels.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addLabelToTask = `-- name: AddLabelToTask :exec
INSERT INTO card_labels (task_id, label_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddLabelToTaskParams struct {
	TaskID  uuid.UUID `json:"task_id"`
	LabelID uuid.UUID `json:"label_id"`
}

func (q *Queries) AddLabelToTask(ctx context.Context, arg AddLabelToTaskParams) error {
	_, err := q.db.Exec(ctx, addLabelToTask, arg.TaskID, arg.LabelID)
	return err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO labels (board_id, name, color)
VALUES ($1, $2, COALESCE($3, '#DADADA'))
RETURNING id, board_id, name, color, created_at
`

type CreateLabelParams struct {
	BoardID uuid.UUID   `json:"board_id"`
	Name    string      `json:"name"`
	Column3 interface{} `json:"column_3"`
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, createLabel, arg.BoardID, arg.Name, arg.Column3)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const listLabelsByBoard = `-- name: ListLabelsByBoard :many
SELECT id, board_id, name, color, created_at
FROM labels
WHERE board_id = $1
ORDER BY name ASC
`

func (q *Queries) ListLabelsByBoard(ctx context.Context, boardID uuid.UUID) ([]Label, error) {
	rows, err := q.db.Query(ctx, listLabelsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskLabels = `-- name: ListTaskLabels :many
SELECT l.id, l.board_id, l.name, l.color, l.created_at
FROM card_labels cl
         JOIN labels l ON l.id = cl.label_id
WHERE cl.task_id = $1
ORDER BY l.name ASC
`

func (q *Queries) ListTaskLabels(ctx context.Context, taskID uuid.UUID) ([]Label, error) {
	rows, err := q.db.Query(ctx, listTaskLabels, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeLabelFromTask = `-- name: RemoveLabelFromTask :exec
DELETE
FROM card_labels
WHERE task_id = $1
  AND label_id = $2
`

type RemoveLabelFromTaskParams struct {
	TaskID  uuid.UUID `json:"task_id"`
	LabelID uuid.UUID `json:"label_id"`
}

func (q *Queries) RemoveLabelFromTask(ctx context.Context, arg RemoveLabelFromTaskParams) error {
	_, err := q.db.Exec(ctx, removeLabelFromTask, arg.TaskID, arg.LabelID)
	return err
}
