// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: rbac_permissions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (key, description)
VALUES ($1, $2)
RETURNING id, key, description, created_at
`

type CreatePermissionParams struct {
	Key         string `json:"key"`
	Description string `json:"description"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission, arg.Key, arg.Description)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions WHERE id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePermission, id)
	return err
}

const getPermissionByKey = `-- name: GetPermissionByKey :one
SELECT id, key, description, created_at FROM permissions WHERE key = $1 LIMIT 1
`

func (q *Queries) GetPermissionByKey(ctx context.Context, key string) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByKey, key)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const grantPermissionToRole = `-- name: GrantPermissionToRole :exec
INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type GrantPermissionToRoleParams struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) GrantPermissionToRole(ctx context.Context, arg GrantPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, grantPermissionToRole, arg.RoleID, arg.PermissionID)
	return err
}

const hasPermission = `-- name: HasPermission :one
SELECT EXISTS (
    SELECT 1
    FROM user_roles ur
             JOIN role_permissions rp ON rp.role_id = ur.role_id
             JOIN permissions p ON p.id = rp.permission_id
    WHERE ur.user_id = $1
      AND p.key = $2
) AS has_permission
`

type HasPermissionParams struct {
	UserID uuid.UUID `json:"user_id"`
	Key    string    `json:"key"`
}

func (q *Queries) HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPermission, arg.UserID, arg.Key)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, key, description, created_at FROM permissions ORDER BY created_at DESC
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPermissionKeys = `-- name: ListUserPermissionKeys :many
SELECT DISTINCT p.key
FROM user_roles ur
         JOIN role_permissions rp ON rp.role_id = ur.role_id
         JOIN permissions p ON p.id = rp.permission_id
WHERE ur.user_id = $1
ORDER BY p.key ASC
`

func (q *Queries) ListUserPermissionKeys(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserPermissionKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePermissionFromRole = `-- name: RevokePermissionFromRole :exec
DELETE FROM role_permissions WHERE role_id = $1 AND permission_id = $2
`

type RevokePermissionFromRoleParams struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) RevokePermissionFromRole(ctx context.Context, arg RevokePermissionFromRoleParams) error {
	_, err := q.db.Exec(ctx, revokePermissionFromRole, arg.RoleID, arg.PermissionID)
	return err
}
