// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: security.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bumpUserTokenVersion = `-- name: BumpUserTokenVersion :exec
UPDATE users
SET token_version = token_version + 1
WHERE id = $1
`

func (q *Queries) BumpUserTokenVersion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, bumpUserTokenVersion, id)
	return err
}

const getUserTokenVersion = `-- name: GetUserTokenVersion :one
SELECT token_version
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserTokenVersion(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getUserTokenVersion, id)
	var token_version int32
	err := row.Scan(&token_version)
	return token_version, err
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_logs (user_id, action, entity, entity_id, metadata, ip_address, user_agent)
VALUES ($1::uuid,
        $2,
        $3,
        $4::uuid,
        COALESCE($5::jsonb, '{}'::jsonb),
        $6,
        $7)
RETURNING id, user_id, action, entity, entity_id, metadata, ip_address, user_agent, created_at
`

type InsertAuditLogParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Action    string      `json:"action"`
	Entity    string      `json:"entity"`
	EntityID  pgtype.UUID `json:"entity_id"`
	Metadata  []byte      `json:"metadata"`
	IpAddress pgtype.Text `json:"ip_address"`
	UserAgent pgtype.Text `json:"user_agent"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.UserID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Metadata,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.Entity,
		&i.EntityID,
		&i.Metadata,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}
