// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: task_column.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTaskInColumn = `-- name: CreateTaskInColumn :one
INSERT INTO tasks (project_id, title, description, status, priority,
                   assignee_id, due_date, board_id, column_id, position,
                   story_points, original_estimate_seconds, remaining_estimate_seconds)
VALUES ($1::uuid,
        $2,
        COALESCE($3::text, ''),
        COALESCE($4::text, 'new'),
        COALESCE($5::int4, 0),
        $6::uuid,
        $7::timestamptz,
        $8::uuid,
        $9::uuid,
        $10::float8,
        $11::float8,
        COALESCE($12::int4, 0),
        COALESCE($13::int4, 0))
RETURNING
    id, project_id, title, description, status, priority, assignee_id, due_date,
    board_id, column_id, position, story_points, original_estimate_seconds, remaining_estimate_seconds,
    created_at, updated_at
`

type CreateTaskInColumnParams struct {
	ProjectID                uuid.UUID          `json:"project_id"`
	Title                    string             `json:"title"`
	Description              pgtype.Text        `json:"description"`
	Status                   pgtype.Text        `json:"status"`
	Priority                 pgtype.Int4        `json:"priority"`
	AssigneeID               pgtype.UUID        `json:"assignee_id"`
	DueDate                  pgtype.Timestamptz `json:"due_date"`
	BoardID                  uuid.UUID          `json:"board_id"`
	ColumnID                 uuid.UUID          `json:"column_id"`
	Position                 float64            `json:"position"`
	StoryPoints              pgtype.Float8      `json:"story_points"`
	OriginalEstimateSeconds  pgtype.Int4        `json:"original_estimate_seconds"`
	RemainingEstimateSeconds pgtype.Int4        `json:"remaining_estimate_seconds"`
}

type CreateTaskInColumnRow struct {
	ID                       uuid.UUID          `json:"id"`
	ProjectID                uuid.UUID          `json:"project_id"`
	Title                    string             `json:"title"`
	Description              string             `json:"description"`
	Status                   string             `json:"status"`
	Priority                 int32              `json:"priority"`
	AssigneeID               pgtype.UUID        `json:"assignee_id"`
	DueDate                  pgtype.Timestamptz `json:"due_date"`
	BoardID                  pgtype.UUID        `json:"board_id"`
	ColumnID                 pgtype.UUID        `json:"column_id"`
	Position                 pgtype.Float8      `json:"position"`
	StoryPoints              pgtype.Float8      `json:"story_points"`
	OriginalEstimateSeconds  int32              `json:"original_estimate_seconds"`
	RemainingEstimateSeconds int32              `json:"remaining_estimate_seconds"`
	CreatedAt                time.Time          `json:"created_at"`
	UpdatedAt                time.Time          `json:"updated_at"`
}

func (q *Queries) CreateTaskInColumn(ctx context.Context, arg CreateTaskInColumnParams) (CreateTaskInColumnRow, error) {
	row := q.db.QueryRow(ctx, createTaskInColumn,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.DueDate,
		arg.BoardID,
		arg.ColumnID,
		arg.Position,
		arg.StoryPoints,
		arg.OriginalEstimateSeconds,
		arg.RemainingEstimateSeconds,
	)
	var i CreateTaskInColumnRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.BoardID,
		&i.ColumnID,
		&i.Position,
		&i.StoryPoints,
		&i.OriginalEstimateSeconds,
		&i.RemainingEstimateSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasksByColumn = `-- name: ListTasksByColumn :many
SELECT id,
       project_id,
       title,
       description,
       status,
       priority,
       assignee_id,
       due_date,
       board_id,
       column_id,
       position,
       story_points,
       original_estimate_seconds,
       remaining_estimate_seconds,
       created_at,
       updated_at
FROM tasks
WHERE column_id = $1
  AND deleted_at IS NULL
ORDER BY position ASC
LIMIT $2 OFFSET $3
`

type ListTasksByColumnParams struct {
	ColumnID pgtype.UUID `json:"column_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type ListTasksByColumnRow struct {
	ID                       uuid.UUID          `json:"id"`
	ProjectID                uuid.UUID          `json:"project_id"`
	Title                    string             `json:"title"`
	Description              string             `json:"description"`
	Status                   string             `json:"status"`
	Priority                 int32              `json:"priority"`
	AssigneeID               pgtype.UUID        `json:"assignee_id"`
	DueDate                  pgtype.Timestamptz `json:"due_date"`
	BoardID                  pgtype.UUID        `json:"board_id"`
	ColumnID                 pgtype.UUID        `json:"column_id"`
	Position                 pgtype.Float8      `json:"position"`
	StoryPoints              pgtype.Float8      `json:"story_points"`
	OriginalEstimateSeconds  int32              `json:"original_estimate_seconds"`
	RemainingEstimateSeconds int32              `json:"remaining_estimate_seconds"`
	CreatedAt                time.Time          `json:"created_at"`
	UpdatedAt                time.Time          `json:"updated_at"`
}

func (q *Queries) ListTasksByColumn(ctx context.Context, arg ListTasksByColumnParams) ([]ListTasksByColumnRow, error) {
	rows, err := q.db.Query(ctx, listTasksByColumn, arg.ColumnID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksByColumnRow
	for rows.Next() {
		var i ListTasksByColumnRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.DueDate,
			&i.BoardID,
			&i.ColumnID,
			&i.Position,
			&i.StoryPoints,
			&i.OriginalEstimateSeconds,
			&i.RemainingEstimateSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveTaskToColumn = `-- name: MoveTaskToColumn :exec
UPDATE tasks
SET column_id  = $2,
    position   = $3,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

type MoveTaskToColumnParams struct {
	ID       uuid.UUID     `json:"id"`
	ColumnID pgtype.UUID   `json:"column_id"`
	Position pgtype.Float8 `json:"position"`
}

func (q *Queries) MoveTaskToColumn(ctx context.Context, arg MoveTaskToColumnParams) error {
	_, err := q.db.Exec(ctx, moveTaskToColumn, arg.ID, arg.ColumnID, arg.Position)
	return err
}

const nextTaskPosition = `-- name: NextTaskPosition :one
SELECT f_next_task_position($1) AS next_pos
`

func (q *Queries) NextTaskPosition(ctx context.Context, pColumnID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, nextTaskPosition, pColumnID)
	var next_pos float64
	err := row.Scan(&next_pos)
	return next_pos, err
}

const reorderTaskPosition = `-- name: ReorderTaskPosition :exec
UPDATE tasks
SET position   = $2,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

type ReorderTaskPositionParams struct {
	ID       uuid.UUID     `json:"id"`
	Position pgtype.Float8 `json:"position"`
}

func (q *Queries) ReorderTaskPosition(ctx context.Context, arg ReorderTaskPositionParams) error {
	_, err := q.db.Exec(ctx, reorderTaskPosition, arg.ID, arg.Position)
	return err
}

const updateTaskEstimates = `-- name: UpdateTaskEstimates :one
UPDATE tasks
SET original_estimate_seconds  = COALESCE($2, original_estimate_seconds),
    remaining_estimate_seconds = COALESCE($3, remaining_estimate_seconds),
    updated_at                 = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, project_id, title, description, status, priority, assignee_id, due_date,
    board_id, column_id, position, story_points, original_estimate_seconds, remaining_estimate_seconds,
    created_at, updated_at
`

type UpdateTaskEstimatesParams struct {
	ID                       uuid.UUID   `json:"id"`
	OriginalEstimateSeconds  pgtype.Int4 `json:"original_estimate_seconds"`
	RemainingEstimateSeconds pgtype.Int4 `json:"remaining_estimate_seconds"`
}

type UpdateTaskEstimatesRow struct {
	ID                       uuid.UUID          `json:"id"`
	ProjectID                uuid.UUID          `json:"project_id"`
	Title                    string             `json:"title"`
	Description              string             `json:"description"`
	Status                   string             `json:"status"`
	Priority                 int32              `json:"priority"`
	AssigneeID               pgtype.UUID        `json:"assignee_id"`
	DueDate                  pgtype.Timestamptz `json:"due_date"`
	BoardID                  pgtype.UUID        `json:"board_id"`
	ColumnID                 pgtype.UUID        `json:"column_id"`
	Position                 pgtype.Float8      `json:"position"`
	StoryPoints              pgtype.Float8      `json:"story_points"`
	OriginalEstimateSeconds  int32              `json:"original_estimate_seconds"`
	RemainingEstimateSeconds int32              `json:"remaining_estimate_seconds"`
	CreatedAt                time.Time          `json:"created_at"`
	UpdatedAt                time.Time          `json:"updated_at"`
}

func (q *Queries) UpdateTaskEstimates(ctx context.Context, arg UpdateTaskEstimatesParams) (UpdateTaskEstimatesRow, error) {
	row := q.db.QueryRow(ctx, updateTaskEstimates, arg.ID, arg.OriginalEstimateSeconds, arg.RemainingEstimateSeconds)
	var i UpdateTaskEstimatesRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.BoardID,
		&i.ColumnID,
		&i.Position,
		&i.StoryPoints,
		&i.OriginalEstimateSeconds,
		&i.RemainingEstimateSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskSprintFields = `-- name: UpdateTaskSprintFields :one
UPDATE tasks
SET title        = COALESCE($2, title),
    description  = COALESCE($3, description),
    status       = COALESCE($4, status), -- optional, bila masih dipakai
    priority     = COALESCE($5, priority),
    assignee_id  = COALESCE($6, assignee_id),
    due_date     = COALESCE($7, due_date),
    story_points = COALESCE($8, story_points),
    updated_at   = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, project_id, title, description, status, priority, assignee_id, due_date,
    board_id, column_id, position, story_points, original_estimate_seconds, remaining_estimate_seconds,
    created_at, updated_at
`

type UpdateTaskSprintFieldsParams struct {
	ID          uuid.UUID          `json:"id"`
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      pgtype.Text        `json:"status"`
	Priority    pgtype.Int4        `json:"priority"`
	AssigneeID  pgtype.UUID        `json:"assignee_id"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	StoryPoints pgtype.Float8      `json:"story_points"`
}

type UpdateTaskSprintFieldsRow struct {
	ID                       uuid.UUID          `json:"id"`
	ProjectID                uuid.UUID          `json:"project_id"`
	Title                    string             `json:"title"`
	Description              string             `json:"description"`
	Status                   string             `json:"status"`
	Priority                 int32              `json:"priority"`
	AssigneeID               pgtype.UUID        `json:"assignee_id"`
	DueDate                  pgtype.Timestamptz `json:"due_date"`
	BoardID                  pgtype.UUID        `json:"board_id"`
	ColumnID                 pgtype.UUID        `json:"column_id"`
	Position                 pgtype.Float8      `json:"position"`
	StoryPoints              pgtype.Float8      `json:"story_points"`
	OriginalEstimateSeconds  int32              `json:"original_estimate_seconds"`
	RemainingEstimateSeconds int32              `json:"remaining_estimate_seconds"`
	CreatedAt                time.Time          `json:"created_at"`
	UpdatedAt                time.Time          `json:"updated_at"`
}

func (q *Queries) UpdateTaskSprintFields(ctx context.Context, arg UpdateTaskSprintFieldsParams) (UpdateTaskSprintFieldsRow, error) {
	row := q.db.QueryRow(ctx, updateTaskSprintFields,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.DueDate,
		arg.StoryPoints,
	)
	var i UpdateTaskSprintFieldsRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.BoardID,
		&i.ColumnID,
		&i.Position,
		&i.StoryPoints,
		&i.OriginalEstimateSeconds,
		&i.RemainingEstimateSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
