// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tasks.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignTask = `-- name: AssignTask :exec
UPDATE tasks
SET assignee_id = $2,
    updated_at  = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

type AssignTaskParams struct {
	ID         uuid.UUID   `json:"id"`
	AssigneeID pgtype.UUID `json:"assignee_id"`
}

func (q *Queries) AssignTask(ctx context.Context, arg AssignTaskParams) error {
	_, err := q.db.Exec(ctx, assignTask, arg.ID, arg.AssigneeID)
	return err
}

const changeTaskStatus = `-- name: ChangeTaskStatus :exec
UPDATE tasks
SET status     = $2,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

type ChangeTaskStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) ChangeTaskStatus(ctx context.Context, arg ChangeTaskStatusParams) error {
	_, err := q.db.Exec(ctx, changeTaskStatus, arg.ID, arg.Status)
	return err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, title, description, status, priority, assignee_id, due_date)
VALUES ($1, $2, COALESCE($3, ''), COALESCE($4, 'new'), COALESCE($5, 0), $6, $7)
RETURNING id, project_id, title, description, status, priority, assignee_id, due_date, created_at, updated_at
`

type CreateTaskParams struct {
	ProjectID  uuid.UUID          `json:"project_id"`
	Title      string             `json:"title"`
	Column3    interface{}        `json:"column_3"`
	Column4    interface{}        `json:"column_4"`
	Column5    interface{}        `json:"column_5"`
	AssigneeID pgtype.UUID        `json:"assignee_id"`
	DueDate    pgtype.Timestamptz `json:"due_date"`
}

type CreateTaskRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	Priority    int32              `json:"priority"`
	AssigneeID  pgtype.UUID        `json:"assignee_id"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.Title,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.AssigneeID,
		arg.DueDate,
	)
	var i CreateTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const forceDeleteTask = `-- name: ForceDeleteTask :exec
DELETE
FROM tasks
WHERE id = $1
`

func (q *Queries) ForceDeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, forceDeleteTask, id)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id,
       project_id,
       title,
       description,
       status,
       priority,
       assignee_id,
       due_date,
       created_at,
       updated_at
FROM tasks
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

type GetTaskByIDRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	Priority    int32              `json:"priority"`
	AssigneeID  pgtype.UUID        `json:"assignee_id"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (GetTaskByIDRow, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i GetTaskByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id,
       project_id,
       title,
       description,
       status,
       priority,
       assignee_id,
       due_date,
       created_at,
       updated_at
FROM tasks
WHERE deleted_at IS NULL
  AND ($3::uuid IS NULL OR project_id = $3::uuid)
  AND ($4::text IS NULL OR status = $4::text)
  AND ($5::uuid IS NULL OR assignee_id = $5::uuid)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTasksParams struct {
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	ProjectID  pgtype.UUID `json:"project_id"`
	Status     pgtype.Text `json:"status"`
	AssigneeID pgtype.UUID `json:"assignee_id"`
}

type ListTasksRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	Priority    int32              `json:"priority"`
	AssigneeID  pgtype.UUID        `json:"assignee_id"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.Limit,
		arg.Offset,
		arg.ProjectID,
		arg.Status,
		arg.AssigneeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksRow
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT id,
       project_id,
       title,
       description,
       status,
       priority,
       assignee_id,
       due_date,
       created_at,
       updated_at
FROM tasks
WHERE project_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTasksByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListTasksByProjectRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	Priority    int32              `json:"priority"`
	AssigneeID  pgtype.UUID        `json:"assignee_id"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

func (q *Queries) ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]ListTasksByProjectRow, error) {
	rows, err := q.db.Query(ctx, listTasksByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksByProjectRow
	for rows.Next() {
		var i ListTasksByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTask = `-- name: SoftDeleteTask :exec
UPDATE tasks
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTask, id)
	return err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title       = COALESCE($2, title),
    description = COALESCE($3, description),
    status      = COALESCE($4, status),
    priority    = COALESCE($5, priority),
    assignee_id = COALESCE($6, assignee_id),
    due_date    = COALESCE($7, due_date),
    updated_at  = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, project_id, title, description, status, priority, assignee_id, due_date, created_at, updated_at
`

type UpdateTaskParams struct {
	ID          uuid.UUID          `json:"id"`
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      pgtype.Text        `json:"status"`
	Priority    pgtype.Int4        `json:"priority"`
	AssigneeID  pgtype.UUID        `json:"assignee_id"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
}

type UpdateTaskRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	Priority    int32              `json:"priority"`
	AssigneeID  pgtype.UUID        `json:"assignee_id"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (UpdateTaskRow, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.DueDate,
	)
	var i UpdateTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
