// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: time_tracking.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addTimeEntry = `-- name: AddTimeEntry :one
INSERT INTO time_entries (task_id, user_id, spent_seconds, work_date, note)
VALUES ($1, $2, $3, COALESCE($4, CURRENT_DATE), COALESCE($5, ''))
RETURNING id, task_id, user_id, spent_seconds, work_date, note, created_at
`

type AddTimeEntryParams struct {
	TaskID       uuid.UUID   `json:"task_id"`
	UserID       uuid.UUID   `json:"user_id"`
	SpentSeconds int32       `json:"spent_seconds"`
	Column4      interface{} `json:"column_4"`
	Column5      interface{} `json:"column_5"`
}

func (q *Queries) AddTimeEntry(ctx context.Context, arg AddTimeEntryParams) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, addTimeEntry,
		arg.TaskID,
		arg.UserID,
		arg.SpentSeconds,
		arg.Column4,
		arg.Column5,
	)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.SpentSeconds,
		&i.WorkDate,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listTimeEntriesByTask = `-- name: ListTimeEntriesByTask :many
SELECT id, task_id, user_id, spent_seconds, work_date, note, created_at
FROM time_entries
WHERE task_id = $1
ORDER BY work_date DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListTimeEntriesByTaskParams struct {
	TaskID uuid.UUID `json:"task_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListTimeEntriesByTask(ctx context.Context, arg ListTimeEntriesByTaskParams) ([]TimeEntry, error) {
	rows, err := q.db.Query(ctx, listTimeEntriesByTask, arg.TaskID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeEntry
	for rows.Next() {
		var i TimeEntry
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.SpentSeconds,
			&i.WorkDate,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumTimeByTask = `-- name: SumTimeByTask :one
SELECT COALESCE(SUM(spent_seconds), 0) AS total_spent_seconds
FROM time_entries
WHERE task_id = $1
`

func (q *Queries) SumTimeByTask(ctx context.Context, taskID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, sumTimeByTask, taskID)
	var total_spent_seconds interface{}
	err := row.Scan(&total_spent_seconds)
	return total_spent_seconds, err
}
